### ISSUE TITLE
Something went wrong! 

### ISSUE THREAD

**Issue by christophersaebo** [NerdyGamer05/CubeScrambler#2]
Hi, i did whats said in the usage tab, i get this error with the same code: Something went wrong!
TypeError: scramblers.scrambler is not a function

Code: 
        const scramblers = require('cube-scramble.js');
        const scrambletype = interaction.options.getString('type')  

        const sequence = scramblers.scrambler(scrambletype); // returns an array

**Comment by christophersaebo** [comment]
When i run This: const scrambler = require('cube-scramble.js');
const types = scrambler.scrambleType; // returns an array
console.log(types)

I get undefined in the console

**Comment by jpatel2005** [comment]
I apologize for the issue. There was an mistake in the documentation. The following code should work using the `scrambleList` attribute.
```js
const scrambler = require('cube-scramble.js');
const types = scrambler.scrambleList; // returns an array
console.log(types);
```

**Comment by christophersaebo** [comment]
Ok, now things work, But is it possible to make it to a wca scrambler? More people might use it then

**Comment by jpatel2005** [comment]
This scrambler will never be official as it was not created by the WCA. Additionally, the WCA [regulations](https://www.worldcubeassociation.org/regulations/#4b3) state that a scrambler must generates random states and find a solution to that state. If that state is considered to be "valid" (such at meeting the minimum move requirement), then a scramble sequence is generated. My scrambler uses random moves and builds scrambles by accounting for past moves, but it is not on par with the official WCA scrambler. I chose not to go with a random state scramble as that is pretty complex and it will take some time to developer. I may create a scrambler in the future that uses this standard but for now I will stick with this.
If you want a scrambler that is closer to official than mine, take a look at [cubing.js](https://github.com/cubing/cubing.js/).

**Comment by christophersaebo** [comment]
I'm gonna just check your source code and see how it's made of I'm gonna try to make my own scrambler package that's close to wca

**Comment by jpatel2005** [comment]
I should warn you that my source code will not be of any benefit to you, since I used random move scrambling, whereas the WCA compliant scrambler uses random state scrambling, then inverses the solution to generate a scramble pattern. The logic behind this algorithm is pretty complex and it cannot be easily extended to other cubes (NxN cubes and the unstandard types). However, feel free to use my source code and I wish you the best of luck with your scrambler!
